model:
    # model_type: seq_2_seq_lm #causal_lm
    model_type: causal_lm 
    pretrained_model_name_or_path: namfam/llama-3.2-1b-instruct__gsm8k_vi
    pretrained_tokenizer_name_or_path: 
    load_in_4bit: true
    load_in_8bit: true
    bnb_4bit_compute_dtype: null
    bnb_4bit_quant_type: "nf4"
    bnb_4bit_use_double_quant: false
    bnb_4bit_quant_storage: "uint8"
    torch_dtype: bfloat16
    attn_implementation: #flash_attention_2
    device_map: null
    low_cpu_mem_usage: null
    lora_adapter: # path to lora adapter

tokenizer:
  tokenizer_args:
      # padding_side: "left"
      max_length: 512
      truncation: True
      padding: max_length
      return_tensors: 'pt'
      add_special_tokens: false
  

prompt:
  use_model_chat_template: false
  use_only_input_text: true
  use_examples: false
  use_context: false
  use_response_format_guide: true

  intro_text: "You are a math expert." 

  instruction_key: #"### Instruction"
  instruction_text: "Solve the following problem carefully and accurately.\nYour response must include two sections:\n- Reason: Provide a step-by-step explanation of how to solve the problem.\n- Answer: Write only the final numerical answer without any additional text, symbols, or units."

  response_format_guide_key: "Format your response exactly as follows:"
  response_format_guide_text: "Solution:\nReason:\n<Step-by-step explanation>\nAnswer:\n<Final numerical result>"

  examples_key: "Here are some examples to guide you:"
  examples_template: |
    - Example {index}:
      Problem:
      {problem}
    
      Solution:
      Reason:
      {reason}
      Answer:
      {answer}

  examples_list:
    - index: 1
      problem: "Weng kiếm được $12 một giờ khi trông trẻ. Hôm qua, cô ấy chỉ trông được 50 phút. Cô ấy kiếm được bao nhiêu tiền?"
      reason: "Weng kiếm được 12/60 = $0.2 mỗi phút.\nLàm việc trong 50 phút, cô ấy kiếm được 0.2 x 50 = $10."
      answer: "10"

    - index: 2
      problem: "Weng kiếm được $12 một giờ khi trông trẻ. Hôm qua, cô ấy chỉ trông được 50 phút. Cô ấy kiếm được bao nhiêu tiền?"
      reason: "Weng kiếm được 12/60 = $0.2 mỗi phút.\nLàm việc trong 50 phút, cô ấy kiếm được 0.2 x 50 = $10."
      answer: "10"
  

  input_key: "Here is the problem:" #"### Problem:"
  input_text: "Một xe máy đi từ A đến B với vận tốc 40 km/h. Sau 2 giờ, một ô tô xuất phát từ A đuổi theo xe máy với vận tốc 60 km/h. Hỏi sau bao lâu ô tô bắt kịp xe máy?"
  
  context_key: "This is context_key"
  context_text: "This is context_text"

  pre_response_text: Now, please solve the problem and provide your response below.
  
  response_key: "Solution:"
  # response_key: "### Solution: Let's think step by step.\n"
  response_text: "Reason:\n5 chiếc xe mô hình có giá $20 x 5 = $100.\n5 chai sơn có giá $10 x 5 = $50.\n5 cọ sơn có giá $2 x 5 = $10.\nVì vậy, Marc đã chi tiêu tổng cộng $100 + $50 + $10 = $160.\nAnswer:\n160"

  end_key: 
  sep: "\n\n"

generate:
  seed: 202502
  use_vllm: False
  do_postprocess: false
  return_full: true
  skip_special_tokens: true
  gen_args:
    max_new_tokens: 512
    max_length: null
    temperature: null
    do_sample: null
    top_p: null
    top_k: null
    # num_beams: 4,    
    # num_return_sequences: 4,
    # return_dict_in_generate: True,
    # output_scores: True,
  
device:
  use_cpu: false
